// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservePoint.Infrastructure.Persistence;

#nullable disable

namespace ReservePoint.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323140541_ChangedBookingPolicy")]
    partial class ChangedBookingPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservePoint.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingGroupId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("ReservePoint.Domain.Entities.BookingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookingGroups");
                });

            modelBuilder.Entity("ReservePoint.Domain.Entities.Booking", b =>
                {
                    b.HasOne("ReservePoint.Domain.Entities.BookingGroup", null)
                        .WithMany("Bookings")
                        .HasForeignKey("BookingGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservePoint.Domain.Entities.BookingGroup", b =>
                {
                    b.OwnsOne("ReservePoint.Domain.Entities.BookingPolicySnapshot", "AppliedPolicy", b1 =>
                        {
                            b1.Property<Guid>("BookingGroupId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxBookingsPerUser")
                                .HasColumnType("integer")
                                .HasColumnName("Policy_MaxBookingsPerUser");

                            b1.Property<int>("MaxDurationHours")
                                .HasColumnType("integer")
                                .HasColumnName("Policy_MaxDurationHours");

                            b1.HasKey("BookingGroupId");

                            b1.ToTable("BookingGroups");

                            b1.WithOwner()
                                .HasForeignKey("BookingGroupId");
                        });

                    b.Navigation("AppliedPolicy")
                        .IsRequired();
                });

            modelBuilder.Entity("ReservePoint.Domain.Entities.BookingGroup", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
