// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservePoint.Infrastructure.Persistence;

#nullable disable

namespace ReservePoint.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservePoint.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ReservePoint.Domain.Entities.Booking", b =>
                {
                    b.OwnsOne("ReservePoint.Domain.Entities.BookingPolicySnapshot", "AppliedPolicy", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("AllowedTimeFrom")
                                .HasColumnType("interval")
                                .HasColumnName("Policy_AllowedTimeFrom");

                            b1.Property<TimeSpan>("AllowedTimeTo")
                                .HasColumnType("interval")
                                .HasColumnName("Policy_AllowedTimeTo");

                            b1.Property<int>("MaxBookingsPerUser")
                                .HasColumnType("integer")
                                .HasColumnName("Policy_MaxBookingsPerUser");

                            b1.Property<int>("MaxDurationHours")
                                .HasColumnType("integer")
                                .HasColumnName("Policy_MaxDurationHours");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("AppliedPolicy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
